# Generated by Django 5.2.4 on 2026-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
